apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: delete-repo
  title: Delete a repository.
  description: "Delete an existing repository in your GitHub organiziation."
spec:
  owner: group:roadie-demo/solutions # TODO: Define who the owner of this template is. This is likely the team who own the relationship with Roadie. e.g. group:customer-name/platform
  type: service

  # These are the steps which are rendered in the frontend with the form input.
  parameters:
    - title: Repository Selection # Title of the first step.
      required:
        - repoSlug
      properties:
        repoSlug:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Repository
            description: Choose the repository to be registered in your catalog.
            path: "proxy/github/api/orgs/roadie-demo/repos" # TODO: Add the name of your GitHub org. e.g. `/orgs/{reporOrg}/repos`
            params:
              per_page: '100'
              page: '{{ parameters.repoPage }}'
            valueSelector: "full_name"
            labelSelector: "name"

        repoPage:
          title: Page Number
          type: number
          default: 1

        authorization:
          title: I have authorization to delete this repository.
          default: false
          type: boolean

  # These are the steps that are executed in series in the scaffolder backend.
  steps:
    - id: deleteRepo
      name: Delete Repository
      action: 'http:backstage:request'
      input:
        method: 'DELETE'
        path: 'proxy/github/api/repos/${{ parameters.repoSlug }}'
  