apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: publish-standalone-tech-docs
  title: Publish a new standalone TechDocs repository and register with Roadie Backstage
  description: "Publish a new repository with a catalog-info.yaml file with your company's standalone TechDocs details."
spec:
  owner: unspecified # TODO: Define who the owner of this template is. This is likely the team who own the relationship with Roadie. e.g. group:customer-name/platform
  type: service

  # These are the steps which are rendered in the frontend with the form input.
  parameters:
    - title: Repository Details # Title of the first step.
      required:
        - name
        - description
      properties:
        repoHost:
          type: string
          default: github.com
          ui:widget: hidden

        gitHubOrg:
          type: string
          default: roadie-demo # TODO: Set your GitHub Org value here.
          ui:widget: hidden

        repoBranch:
          type: string
          default: main # TODO: Define your expected default branch.
          ui:widget: hidden

        name:
          title: Name
          type: string
          default: company-docs # TODO: Set your default name for the documentation repository here.

        description:
          title: Description
          decription: A Detailed decription allows for the documentation catalog entry to be easily found and understood in the Roadie Backstage tenant.
          type: string

        lifecycle:
          title: Lifecycle
          description: The initial lifecycle state of the documentation stand-alone repo.
          type: string
          default: production # TODO: Add your most common lifecycle state here.

        owner:
          title: Owner
          type: string
          description: Owner of the documentation catalog entity.
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group # TODO: Decide if you want to allow setting owner by user, group, or both. e.g. [Group, User]
        
        documentationGrouping:
          title: Documentation Groupings
          description: Documentation grouping can be departments or cohorts. Each grouping with get their own subdirectory and index page.
          type: array
          items:
            type: string
            title: A Documentation Grouping

  # These are the steps that are executed in series in the scaffolder backend.
  steps:
    - id: fetchCatalogTemplate
      name: Fetch the catalog-info.yaml file.
      action: fetch:template
      input:
        url: ./skeleton
        templateFileExtension: .njk
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          repoSlug: ${{ parameters.gitHubOrg }}/${{ parameters.name }}
          lifecycle: ${{ parameters.lifecycle }}

    - id: fetchTechDocsTemplate
      name: Create repo root TechDocs entry.
      action: fetch:template
      input:
        url: ./techDocs
        templateFileExtension: .njk
        targetPath: ./docs
        values:
          name: ${{ parameters.name }}

    - id: fetchdocumentationGroupingTemplate
      name: Create TechDocs subdirectories.
      each: ${{ parameters.documentationGrouping }}
      action: fetch:template
      input:
        url: ./techDocs
        templateFileExtension: .njk
        targetPath: ./docs/${{ each.value | replace(" ", "-") | lower }}
        values:
          name: ${{ each.value | replace(" ", "-") | lower }}

    - id: publishRepo
      name: Publish New Repository.
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoHost }}?owner=${{ parameters.gitHubOrg }}&repo=${{ parameters.name }}
        repoVisibility: private
        defaultBranch: ${{ parameters.repoBranch }}
        title: Publish new Repository
        description: Publish a new repository for ${{ parameters.name }} to Github.
  
  # These are the outputs from the backend steps, and can be displayed in the frontend after completion.
  output:
    links:
      - title: View the published repo on GitHub
        icon: github
        url: ${{ steps['publishRepo'].output.remoteUrl }}