apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-gh-action
  title: Trigger GitHub Action
  description: ""
spec:
  owner: group:roadie-demo/solutions # TODO: Define who the owner of this template is. This is likely the team who own the relationship with Roadie. e.g. group:customer-name/platform
  type: service

  # These are the steps which are rendered in the frontend with the form input.
  parameters:
    - title: Component Location # Title of the second step.
      properties:
        entity:
          type: string
          ui:field: EntityPicker

        workflow:
          title: Workflow
          description: Select the workflow you would like to run.
          type: string
          enum:
            - 'manual.yml'


  # These are the steps that are executed in series in the scaffolder backend.
  steps:
    - id: log-result
      action: debug:log
      name: Log Entity chosen
      input:
        message: "Retrieving catalog manifest from ${{ parameters.entity }}"
    - id: retrieve-entity-info
      name: Retrieve Entity information from Roadie
      action: http:backstage:request
      input:
        method: 'GET'
        path: "/catalog/entities/by-name/${{ parameters.entity | replace(':', '/') }}"

    - id: log-result
      action: debug:log
      name: Log identified manifest location
      input:
        message: "Retrieving catalog manifest from ${{ steps['backstage_request'].output.body.metadata.annotations['backstage.io/managed-by-origin-location'] }}"

    - id: identify-repo-and-owner
      name: Identify repository and owner
      action: roadiehq:utils:jsonata
      input:
        data: "${{ steps['backstage_request'].output.body }}"
        expression: '$.metadata.annotations.(
                      $slug := $substringAfter($."backstage.io/managed-by-location", "url:https://github.com/");
                      $owner := $substringBefore($slug, "/");
                      {
                          "slug": $slug,
                          "owner": $owner,
                          "repo": $substringBefore($substringAfter($slug & $owner & "/", "/"), "/")
                      }
                    )'

    - id: log-result
      action: debug:log
      name: Log Entity parsing
      input:
        message: Running GH Action against repo ${{ steps['identify-repo-and-owner'].output.result.repo }} owned by ${{ steps['identify-repo-and-owner'].output.result.owner }}

    - id: trigger-gh-action
      name: Trigger GH Action
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=${{ steps['identify-repo-and-owner'].output.result.owner }}&repo=${{ steps['identify-repo-and-owner'].output.result.repo }}
        workflowId: ${{ parameters.workflow }}
        branchOrTagName: 'main'
