apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-gh-action
  title: Trigger GitHub Action
  description: ""
spec:
  owner: group:roadie-demo/solutions # TODO: Define who the owner of this template is. This is likely the team who own the relationship with Roadie. e.g. group:customer-name/platform
  type: service

  # These are the steps which are rendered in the frontend with the form input.
  parameters:
    - title: Select Component # Title of the second step.
      properties:
        entity:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            path: "catalog/entities"
            params:
              filter: 'kind=component,metadata.annotations.github.com/project-slug'
            valueSelector: "metadata.annotations['github.com/project-slug']"
            labelSelector: 'metadata.name'

    - title: Select Workflow # Title of the second step.
      properties:
        workflow:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Workflows
            description: Choose the workflow to be run.
            path: "proxy/github/api/repos/{{ parameters.entity }}/actions/workflows"
            valueSelector: "workflows.[].['name']"
            labelSelector: "workflows.[].['path']"


  # These are the steps that are executed in series in the scaffolder backend.
  steps:
    - id: log-result
      action: debug:log
      name: Log Entity chosen
      input:
        message: "${{ parameters.entity }} selected to run GH Action against."

    - id: split-slug
      name: Split the slug into owner and repo
      action: roadiehq:utils:jsonata
      input:
        data: "${{ parameters.entity }}"
        expression: '$.(
                      {
                          "owner": $substringBefore($, "/"),
                          "repo": $substringAfter($, "/")
                      }
                    )'

    - id: parse-workflow-file-name
      name: Parse workflow file name
      action: roadiehq:utils:jsonata
      input:
        data: "${{ parameters.workflow }}"
        expression: '$.(
                      $pathParts := $split($, "/")
                      {
                        fileName: $pathParts.[$count($pathParts) - 1]
                      }
                    )'

    - id: trigger-gh-action
      name: Trigger GH Action
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=${{ steps['split-slug'].output.result.owner }}&repo=${{ steps['split-slug'].output.result.repo }}
        workflowId: ${{ steps['parse-workflow-file-name'].output.result.fileName
        branchOrTagName: 'main'
